In [1]:
# INSTALLING NUMPY
# This command installs the NumPy library if it's not already installed
# NumPy is the fundamental package for scientific computing in Python

!pip install numpy

In [3]:
# IMPORTING NUMPY
# Import NumPy with the alias 'np' - this is the standard convention
# NumPy provides support for large, multi-dimensional arrays and matrices

import numpy as np

In [11]:
# CREATING A 1D ARRAY WITH SPECIFIC DATA TYPE
# np.array() creates a NumPy array from a Python list
# dtype=np.int16 specifies the data type as 16-bit integer (saves memory)
# This creates a 1-dimensional array with 5 elements

a=np.array([1,2,3,4,5],dtype=np.int16)
print(a)

[1 2 3 4 5]


In [5]:
# CREATING A 2D ARRAY (MATRIX)
# This creates a 2x3 matrix (2 rows, 3 columns)
# The inner lists represent rows, and elements within each list represent columns
# dtype defaults to float64 when using decimal numbers

b=np.array([[1.0,2.0,3.0],[1.2,2.3,4.5]])
print(b)

[[1.  2.  3. ]
 [1.2 2.3 4.5]]


In [6]:
# GETTING ARRAY DIMENSIONS
# .ndim returns the number of dimensions of the array
# 1D array = 1, 2D array = 2, 3D array = 3, etc.

a.ndim

1

In [9]:
# GETTING ARRAY SHAPE
# .shape returns a tuple with the size of each dimension
# For 2D arrays: (rows, columns)
# For 1D arrays: (elements,)


b.shape

(2, 3)

In [12]:
# GETTING ARRAY DATA TYPE
# .dtype returns the data type of the array elements
# Shows the precision and type of numbers stored

a.dtype

dtype('int16')

In [13]:
# GETTING SIZE OF EACH ELEMENT IN BYTES
# .itemsize returns the size of each array element in bytes
# Useful for memory optimization and understanding data storage

a.itemsize

2

In [16]:
# GETTING TOTAL MEMORY USAGE
# .nbytes returns the total number of bytes consumed by the array
# This is the product of .itemsize and the total number of elements

a.nbytes #for getting total size

10

Accessing/Changing specific elements,rows,coloumns,etc

In [18]:
# CREATING A 2D ARRAY FOR INDEXING EXAMPLES
# This creates a 2x7 matrix (2 rows, 7 columns)
# We'll use this to demonstrate various indexing techniques

a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# BASIC INDEXING AND SLICING TECHNIQUES
# a[row, column] - access specific element at row, column position
# a[row, :] - get entire row (all columns)
# a[:, column] - get entire column (all rows)
# a[row, start:end:step] - slice with start, end, and step values

print(a[1,5])
#get specific row
print(a[0,:])
#get specific coloumns
print(a[:,1])
#some fancy things [start:end:step]
print(a[0,1:6:2])

13
[1 2 3 4 5 6 7]
[2 9]
[2 4 6]


In [25]:
# MODIFYING ARRAY ELEMENTS
# You can change individual elements by assigning new values
# This modifies the original array in-place

a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [28]:
# MODIFYING ENTIRE ROWS OR COLUMNS
# You can assign new values to entire rows or columns
# This is very useful for data manipulation and preprocessing

a[:,2]=5
print(a)
a[:,4]=[100,1]
print(a)

[[  1   2   5   4 100   6   7]
 [  8   9   5  11   1  20  14]]
[[  1   2   5   4 100   6   7]
 [  8   9   5  11   1  20  14]]


In [31]:
# CREATING 3D ARRAYS
# 3D arrays have 3 dimensions: (layers, rows, columns)
# Think of it as multiple 2D matrices stacked on top of each other

b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# INDEXING 3D ARRAYS
# For 3D arrays: b[layer, row, column]
# Indexing works from outside to inside (left to right)

print(b[0,1,1])

4


In [35]:
# SLICING 3D ARRAYS
# You can slice along any dimension
# b[:,1,:] means: all layers, row 1, all columns

print(b[:,1,:])

[[3 4]
 [7 8]]


In [37]:
# MODIFYING 3D ARRAYS
# You can replace entire sections of 3D arrays
# The replacement array must match the shape of the section being replaced

b[0,:,:]=[[100,1],[200,2]]
print(b)

[[[100   1]
  [200   2]]

 [[  5   6]
  [  7   8]]]


Initialzing different types of arrays 

In [ ]:
# COMMON ARRAY INITIALIZATION FUNCTIONS
# np.zeros() - creates array filled with zeros
# np.ones() - creates array filled with ones
# np.full() - creates array filled with any specified value
# np.random functions - create arrays with random values
# np.identity() - creates identity matrix (diagonal = 1, rest = 0)

np.zeros((3,4))
#all 1s
np.ones((2,3,4),dtype=np.int16)
#any other number
np.full(5,99)
#random decimal numbers
np.random.rand(4,2)
np.random.random_sample(b.shape) #to get same shape 
#random integers numbers
np.random.randint(7,15,size=(3,3))
#identity matrix
np.identity(3)
#repeat an array
arr=np.array([[1,2,3]])
np.repeat(arr, 3,axis=0) #repeat 3 times along axis 0


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [54]:
# PRACTICAL EXAMPLE: CREATING A PATTERN
# This demonstrates combining multiple NumPy operations to create a specific pattern
# Shows how to use slicing and assignment together effectively

op=np.ones((5,5))
op[1:4,1:4]=np.zeros((3,3))
op[2,2]=9
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### be careful when copying arrays!!!
### when we use = to copy, so changes made in one array stay for both of them 
### so use .copy() function

Mathematics

In [41]:
# CREATING ARRAY FOR MATH OPERATIONS
# Simple 1D array to demonstrate mathematical operations

a=np.array([1,2,3,4])

In [42]:
# ELEMENT-WISE ARITHMETIC OPERATIONS
# These operations are applied to each element of the array
# Broadcasting: scalar operations are applied to every element

a+2
a-2
a*2
a/2

array([0.5, 1. , 1.5, 2. ])

In [43]:
# ARRAY-TO-ARRAY OPERATIONS
# When operating on two arrays, operations are element-wise
# Arrays must have the same shape (or be broadcastable)

b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [44]:
# POWER OPERATIONS
# ** performs element-wise exponentiation

a**2

array([ 1,  4,  9, 16])

In [45]:
# TRIGONOMETRIC FUNCTIONS
# NumPy provides mathematical functions that work on arrays
# All functions are applied element-wise

np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [46]:
# MATRIX MULTIPLICATION
# np.matmul() performs matrix multiplication (not element-wise)
# Matrix dimensions must be compatible: (m,n) × (n,p) = (m,p)

a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [47]:
# MATRIX DETERMINANT
# np.linalg.det() calculates the determinant of a square matrix
# Determinant is a scalar value that characterizes the matrix

c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [48]:
# LINEAR ALGEBRA MODULE
# np.linalg contains many linear algebra functions
# Check NumPy documentation for complete list of available functions

#see documentation for more stuff

Statistics

In [49]:
# CREATING ARRAY FOR STATISTICS
# 2D array to demonstrate statistical operations along different axes

stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [50]:
# MINIMUM AND MAXIMUM VALUES
# axis parameter determines the direction of operation
# axis=0: operate along columns, axis=1: operate along rows

np.min(stats,axis=1)  #min along rows
np.max(stats,axis=0)  #max along columns
np.min(stats) #min of full maxtrix

np.int64(1)

In [51]:
# SUMMATION OPERATIONS
# np.sum() adds up all elements or along specified axes
# Useful for calculating totals, means, and other aggregations

np.sum(stats,axis=0) #sum along columns
np.sum(stats,axis=1) #sum along rows
np.sum(stats) #sum of full matrix

np.int64(21)

Reorganizing Arrays

In [52]:
# RESHAPING ARRAYS
# .reshape() changes the shape of an array without changing the data
# Total number of elements must remain the same
# Returns a new array (doesn't modify the original)

before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((8,1)) #as long as elements are same anything can be new shape
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [53]:
# VERTICAL STACKING
# np.vstack() combines arrays vertically (stacking rows)
# All arrays must have the same number of columns
# Useful for combining datasets or creating larger matrices

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
v3=np.array([9,10,11,12])
v_stacked=np.vstack((v1,v2,v3,v2))
print(v_stacked)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 5  6  7  8]]


In [54]:
# HORIZONTAL STACKING
# np.hstack() combines arrays horizontally (stacking columns)
# All arrays must have the same number of rows
# Useful for adding features to datasets

h1=np.ones((2,4))
h2=np.zeros((2,2))
hstacked=np.hstack((h1,h2))
print(hstacked)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


Miscellanceous 

Load Data from a file

In [55]:
# LOADING DATA FROM FILES
# np.genfromtxt() reads data from text files
# delimiter specifies how columns are separated
# .astype() converts data to specific data type
# .reshape() reorganizes the loaded data

data = np.genfromtxt('data.txt',delimiter=',')  #load data from a file
data.astype('int32')
data.reshape(9,3,2)
print(data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


Boolean Masking And advanced indexing

In [56]:
# BOOLEAN MASKING
# Creates a boolean array where each element is True/False based on condition
# data>50 returns array of same shape with True where condition is met

data>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [57]:
# USING BOOLEAN MASK FOR FILTERING
# data[data>50] returns only elements where the condition is True
# This is a very efficient way to filter arrays

data[data>50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [59]:
# ADVANCED INDEXING WITH LISTS
# You can use lists of indices to select specific elements
# This is different from slicing - you can select non-consecutive elements

a=np.array([1,2,3,4,5,6,7,8,9])
a[[0,2,-1]]

array([1, 3, 9])

In [65]:
# COMPLEX INDEXING EXAMPLES
# This demonstrates various advanced indexing techniques
# Combining slicing with advanced indexing for complex selections

b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
b[2:4,0:2]
b[[0,1,2,3],[1,2,3,4]]
b[[0,-2,-1],-2:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
a=np.arange(10)
out=a.copy()
out=out[]
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])